version: '3'

networks:
  nginx-php8-node:

services:

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8-service
    networks:
      - nginx-php8-node

  php8-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php8-node
    user: 1000:1000

  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php8-node
